with AAA.Strings;
with CLIC.TTY;
with Ada.Text_IO;
private with GNAT.Strings;

package Commands.Destroy is

  package IO renames Ada.Text_IO;
  package TT renames CLIC.TTY;

  type Command is new Commands.Command with private;

  overriding function Name (Cmd : Command) return CLIC.Subcommand.Identifier is
   ("destroy");

  overriding procedure Execute
   (Cmd : in out Command; Args : AAA.Strings.Vector);

  overriding function Long_Description
   (Cmd : Command) return AAA.Strings.Vector is
   (AAA.Strings.Empty_Vector.Append
     ("Destroys code generated by" & " " & TT.Terminal("generate") & " " & "command.")
     .New_Line
     );

  overriding procedure Setup_Switches
   (Cmd    : in out Command;
    Config : in out CLIC.Subcommand.Switches_Configuration);

  overriding function Short_Description (Cmd : Command) return String is
     ("Destroys code generated by" & " " & TT.Terminal("generate") & " " & "command.");

  overriding function Usage_Custom_Parameters (Cmd : Command) return String is
   ("");

private

  type Command is new Commands.Command with null record;

end Commands.Destroy;